name: 'google_play'
version: '1.0.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
vars:
  google_play:
    stats_installs_app_version: "{{ source('google_play', 'stats_installs_app_version') }}"
    stats_crashes_app_version: "{{ source('google_play', 'stats_crashes_app_version') }}"
    stats_ratings_app_version: "{{ source('google_play', 'stats_ratings_app_version') }}"
    stats_installs_device: "{{ source('google_play', 'stats_installs_device') }}"
    stats_ratings_device: "{{ source('google_play', 'stats_ratings_device') }}"
    stats_installs_os_version: "{{ source('google_play', 'stats_installs_os_version') }}"
    stats_ratings_os_version: "{{ source('google_play', 'stats_ratings_os_version') }}"
    stats_crashes_os_version: "{{ source('google_play', 'stats_crashes_os_version') }}"
    stats_installs_country: "{{ source('google_play', 'stats_installs_country') }}"
    stats_ratings_country: "{{ source('google_play', 'stats_ratings_country') }}"
    stats_store_performance_country: "{{ source('google_play', 'store_performance_country') }}"
    stats_store_performance_traffic_source: "{{ source('google_play', 'store_performance_source') }}"
    stats_installs_overview: "{{ source('google_play', 'stats_installs_overview') }}"
    stats_crashes_overview: "{{ source('google_play', 'stats_crashes_overview') }}"
    stats_ratings_overview: "{{ source('google_play', 'stats_ratings_overview') }}"
    earnings: "{{ source('google_play', 'earnings') }}"
    financial_stats_subscriptions_country: "{{ source('google_play', 'subscriptions_country') }}"
    country_codes: "{{ ref('google_play__country_codes') }}"
models:
  google_play:
    +schema: google_play
    +materialized: table
    intermediate:
      +materialized: ephemeral
      int_google_play__earnings:
        +materialized: view    
    staging:
      +schema: google_play_source
      +materialized: table
      tmp:
        +materialized: view
